repository:
  name: create-react-app
  private: true
  default_branch: develop
  has_issues: true
  has_wiki: true
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

# NOTE: The APIs needed for this plugin are not supported yet by GitHub Apps
# https://developer.github.com/v3/apps/available-endpoints/
# teams:
#   - name: tech
#     permission: push
#   - name: qa
#     permission: push
#   - name: product
#     permission: pull

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        # Still in alpha
        # required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/drone/pr
          - continuous-integration/drone/push
          - ProntoPro/rex/pr/labels
          - ProntoPro/rex/pr/milestone
      enforce_admins: true
      restrictions:
        users:
          - omissis
          - filipposarzana
        teams:
          - teamleaders

  - name: develop
    protection:
      required_pull_request_reviews:
        # Still in alpha
        # required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/drone/pr
          - continuous-integration/drone/push
          - ProntoPro/rex/pr/labels
          - ProntoPro/rex/pr/milestone
      enforce_admins: true
      restrictions:
        users: []
        teams:
          - backend
          - frontend

  - name: release/*
    protection:
      required_pull_request_reviews:
        # Still in alpha
        # required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/drone/pr
          - continuous-integration/drone/push
          - ProntoPro/rex/pr/labels
          - ProntoPro/rex/pr/milestone
      enforce_admins: true
      restrictions:
        users: []
        teams:
          - backend
          - frontend

labels:
  - name: "tribe/CORE :dart:"
    color: b0bec5
  - name: "tribe/GROWTH :chart_with_upwards_trend:"
    color: b0bec5

  - name: area/WEB
    color: fef2c0
  - name: area/ANDROID
    color: fef2c0
  - name: area/IOS
    color: fef2c0
  - name: area/TECH
    color: fef2c0

  - name: kind/RELEASE
    color: 01deff
  - name: kind/ENHANCEMENT
    color: 006b75
  - name: kind/CLEANUP
    color: 608000
  - name: kind/CHANGE-REQUEST
    color: ffab40
  - name: kind/BUG
    color: fc2929
  - name: kind/DEFECT
    color: e99695
  - name: kind/FEATURE
    color: 5319e1
  - name: kind/DEPRECATION
    color: 7c3626

  - name: status/CR-NEEDED
    color: fbca04
  - name: status/CR-ISSUES-FOUND
    color: d93f0b
  - name: status/OK-TO-MERGE
    color: 00cc00
  - name: status/HELP-WANTED
    color: 9c27b0
  - name: status/NEEDS-REBASE
    color: 666633
  - name: status/ON-HOLD
    color: 365181
  - name: status/WIP
    color: bfd4f2
