clone:
  git:
    image: plugins/git:next

pipeline:
  publish:
    image: plugins/npm
    folder: packages/react-scripts
    username: michaelgenesini
    email: michael.genesini@prontopro.it
    secrets:
      - NPM_TOKEN
    when:
      branch:
        - prontopro-react-scripts@2.1.1
      event:
        - tag
