clone:
  git:
    image: plugins/git:next

pipeline:
  publish:
    image: plugins/npm
    settings:
      username: michaelgenesini
      password:
        from_secret: ${NPM_API_KEY}
      email: michael.genesini@prontopro.it
      folder: packages/react-scripts
    when:
      branch:
        - prontopro-react-scripts@2.1.1
      event:
        - tag
